### ISSUE TITLE
Can't install RoundedBoxView package on Profile259

### ISSUE THREAD

**Issue by codercampos** [paulpatarinski/Xamarin.Forms.Plugins#111]
Using Xamarin.Forms with Profile 259 does not let me install this package. There is a reason of this or this is not going to be available on this profile.

Regards

**Comment by kikolopes90** [comment]
same here

**Comment by kikolopes90** [comment]
same here

**Comment by kikolopes90** [comment]
I already solved this problem! 👍

https://forums.xamarin.com/discussion/84642/cannot-remove-windows-phone-silverlight-in-visual-studio#latest

**Comment by codercampos** [comment]
Thank you! Also, you can modify your project by doing Right Click > Options(Properties) on Xamarin Studio (Visual Studio for Mac) and in the General Tab change your profile.

Thanks @kikolopes90 for your solution also. Supporting  Profile 259 is to keep compatibility with the default Xamarin Forms XAML Pages template

**Comment by codercampos** [comment]
#123

**Comment by codercampos** [comment]
#123 Here is a pull request for this so there is no reason to keep this issue open
