### ISSUE TITLE
RoundedBoxViev change BackgroundColor on TapGesture (Andoind bug)

### ISSUE THREAD

**Issue by roninua** [paulpatarinski/Xamarin.Forms.Plugins#112]
I set on tap change  _myRBVname.BackgroundColor = Color.FromHex("#FF0000");_ 
And my RoundedBox BG set red background with no rounded border, but in iOS - CornerBorder is still rounded.

EX: i have blue backround rounded box (corner=50) circle. 
on tap - i want change background to red.
When i tap - round transforming to square with red background.
This is on Android, but in iOS simulator - circle not changes and stay a circle.

I try with your example and not a change a _myRBVname.BackgroundColor = Color.FromHex("#FF0000");_ and change (Styles)Setters... but it have same effect.

Anybody can understand why it happens? And how it fix?
I need round buttons, rounded UI elements in XF and do interactions with this, but my brain explodes!

**Comment by oddbear** [comment]
Dublicate from https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/100 ?
In that case, pending solution in PR https://github.com/paulpatarinski/Xamarin.Forms.Plugins/pull/108
