### ISSUE TITLE
Under Android SVG size uses pixels instead of device independent pixels

### ISSUE THREAD

**Issue by philipag** [paulpatarinski/Xamarin.Forms.Plugins#16]
It used to be that width and height were in DIP (like the rest of XF) but now the SVG specified width/height is used as the bitmap pixel size.  This causes the resultant image to be grainy.

To confirm with XF this should be changed back to DIP.

**Comment by paulpatarinski** [comment]
Hey @philipag Great job spotting this.

I pushed in a fix it is in version 17.

https://www.nuget.org/packages/Xam.Plugins.Forms.Svg/1.0.0.17

The images should be back to crispy clean :) 

Cheers
Paul

**Comment by philipag** [comment]
Thanks!
