### ISSUE TITLE
SVG for iOS isn't rendering

### ISSUE THREAD

**Issue by tate-u** [paulpatarinski/Xamarin.Forms.Plugins#17]
Hi Paul, I've been trying to get iOS to render my svg's for a couple hours now and have no success. It works great for Android. Any suggestions?

- I've verified the embedded resource path is correct
- The control is rendering background color, width, height
- Android doesnt have any issues with the same code
- On droid/win we call SvgImageRenderer.Init() as detailed in the docs. But not doing this for ios since the method doesn't seem to be available.

Thanks!

**Comment by paulpatarinski** [comment]
@tate-u Sorry you went through all this trouble. The SvgImageRenderer.Init() is not there yet because there is not support for iOS yet. I am working on implementing iOS though. It is one of my highest priorities so I will keep this issue open for now and post progress here.

**Comment by tate-u** [comment]
Ah...well that makes more sense now. I was thinking we didn't need to call Init in iOS for some reason.
No reason to be sorry, and thanks for dedicating time to create this control!

**Comment by paulpatarinski** [comment]
Quick update on this. There are several approaches to implement svgs on iOS : 

- Create iOS bindings for something like https://github.com/SVGKit/SVGKit
- Implement from scratch
- Port an existing .Net SVG library to iOS 
- Improve an existing cross platform SVG library like : https://github.com/praeclarum/NGraphics to add support for more shapes. 

I have decided to take the 4th approach by forking NGraphics and then replacing the SVGParser with a more robust parser from a .NET SVG Library (http://www.codeproject.com/Articles/127039/SharpVectors-SVG-Reloaded-An-Introduction).

If you want to follow the progress more closely star : https://github.com/paulpatarinski/NGraphics

I am probably about 1-2 weeks away from having most of the shapes working and tested, but in the end there will be a much more performant/stable implementation for both iOS and Android. 

Cheers
Paul

**Comment by tate-u** [comment]
Looking forward to it!

**Comment by paulpatarinski** [comment]
Update : Got iOS working last night. Need to put some finishing touches. I will be releasing an Alpha some time this week.

**Comment by paulpatarinski** [comment]
@tate-u http://www.nuget.org/packages/Xam.Plugins.Forms.Svg/ 
v >= 1.0.0.18 adds iOS Svg support. 
There is some known missing functionality (support for gradients, animations...), but for the most part most basic svgs should render properly. Let me know if you are having issues.
