### ISSUE TITLE
Unable to resolve SVG.Forms.Plugin.iOS

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#28]
I am trying to use the SVG plugin, but the class `SVG.Forms.Plugin.iOS` can't be resolved in the `AppDelegate.cs` file. Is there a different way other than what's done in the samples to get this to work in iOS? This is in a PCL project btw.

**Comment by paulpatarinski** [comment]
Hey @JoshuaNovak919  sorry for the late response. 

This was an issue with the nuspec. It is fixed in 1.0.0.20

https://www.nuget.org/packages/Xam.Plugins.Forms.Svg/

Let me know if you are still seeing the issue. 

Paul

**Comment by JoshuaNovak919** [comment]
I'm trying to test it, but I keep having an issue with Xamarin Studio not being able to restore the nuget. It looks like it's an issue with the name. Some parts of the package reference 'SVG' and some parts use 'Svg'. I'm thinking maybe that's why it's have trouble finding it to restore it.

**Comment by JoshuaNovak919** [comment]
I finally got the plugin to work. I ended up having two issue I had to fix.

**Issue 1:**
I had to change the name of the packages folder from `Xam.Plugins.Forms.Svg.1.0.0.20` to `Xam.Plugins.Forms.SVG.1.0.0.20` and the file `Xam.Plugins.Forms.Svg.1.0.0.20.nupkg` to `Xam.Plugins.Forms.SVG.1.0.0.20.nupkg` to get it to even load properly. You should push an update that fixes this letter case issue.

**Issue 2:**
I also had an issue with the svgs not being found. I guess you need to set the build action of the svgs to embedded resource (right click on each resource to set) or they won't load properly. It would probably be good to put that in the docs.

**Comment by JoshuaNovak919** [comment]
@paulpatarinski I am going to mark this bug as resolved since the particular issue mentioned is resolved, but i'll open two more issues for the new problems i've found.
