### ISSUE TITLE
Package cannot be resolved due to case sensitivity issue

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#29]
The plugin has a name case sensitivity issue which is causing the package to say it cannot be resolved. It is because it is looking for a folder named `Xam.Plugins.Forms.SVG.1.0.0.20`, but the folder is actually named `Xam.Plugins.Forms.Svg.1.0.0.20`. It is also looking for the file `Xam.Plugins.Forms.SVG.1.0.0.20.nupkg`, but the file is named `Xam.Plugins.Forms.Svg.1.0.0.20.nupkg`. If I go in an manually change the file names it works.

**Changes:**
Name of the packages folder from `Xam.Plugins.Forms.Svg.1.0.0.20` to `Xam.Plugins.Forms.SVG.1.0.0.20`

Name of file `Xam.Plugins.Forms.Svg.1.0.0.20.nupkg` to `Xam.Plugins.Forms.SVG.1.0.0.20.nupkg`

**Comment by JoshuaNovak919** [comment]
Any update on when this will be fixed?

**Comment by JoshuaNovak919** [comment]
This happens in Xamarin Studio, but probably not Visual Studio btw. Since Macs are case sensitive and Windows doesn't really care.

**Comment by paulpatarinski** [comment]
That explains why I have not encountered it. I work mostly through VS. I will fix this some time this week.

**Comment by paulpatarinski** [comment]
This should be fixed in versions >= 1.0.0.21.

https://www.nuget.org/packages/Xam.Plugins.Forms.Svg/

@JoshuaNovak919 can you make sure you are no longer seeing the issue?

**Comment by JoshuaNovak919** [comment]
@paulpatarinski Seems to be working great now. Thanks!!
