### ISSUE TITLE
Update NuGet with Unified iOS support 

### ISSUE THREAD

**Issue by jamesmontemagno** [paulpatarinski/Xamarin.Forms.Plugins#3]
Hey there! With 1.3.1 now on stable with Unified support it would be great if you could update the plugin with this support. I created a short How To video on how to do this: https://www.youtube.com/watch?v=nF8DbL-PVKw

**Comment by paulpatarinski** [comment]
Hey James, 

Should I do this even if I don't have an iOS implementation?

Cheers

**Comment by jamesmontemagno** [comment]
Would still be a good idea to do it so the package will at least install. Is there any reason for not having the iOS implementations? Limitations?

**Comment by paulpatarinski** [comment]
Don't have a Mac. I was hoping someone would help out with the iOS implementation (posted on the forum), but no volunteers.

**Comment by jamesmontemagno** [comment]
Gotcha gotcha... hmmm I will try to do it this week :)

On Sun, Jan 18, 2015 at 6:58 PM, Paul P <notifications@github.com> wrote:

> Don't have a Mac. I was hoping someone would help out with the iOS
> implementation (posted on the forum), but no volunteers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/3#issuecomment-70441005>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>

**Comment by paulpatarinski** [comment]
Hey James, 
Any luck getting iOS working? Also would like to get your opinion on the ExtendedMap plugin (I am missing iOS implementation for that as well)
