### ISSUE TITLE
SVGs not found

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#30]
To get the SVGs to work when they are in the `Images` folder like in your examples you need to right click on them and select `Build Action > EmbeddedResource` or they won't load properly and you will get an error that they can't be found. It would be good to add this to the docs so others know.

**Comment by paulpatarinski** [comment]
Hey @JoshuaNovak919 

It is mentioned under the docs under the you MUST section

https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG

I will make it red so that is more noticable
