### ISSUE TITLE
Navigation.RemovePage on page with SVG causes error

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#31]
If you use `Navigation.RemovePage` on a page that is using an SVG it throws the error `Object reference not set to an instance of an object`. Anyone have any ideas how to fix this or if it is a package issue?

**Comment by erikarenhill** [comment]
I think that my pull request solves this too. https://github.com/paulpatarinski/Xamarin.Forms.Plugins/pull/34

**Comment by paulpatarinski** [comment]
@JoshuaNovak919 this should be resolved in >= 1.0.0.24. @erikarenhill thanks for the PR. I have implemented the custom renderer fix. I will close the PR since there is no need for the Forms upgrade yet

**Comment by erikarenhill** [comment]
Thanks @paulpatarinski , the form upgrades were pushed to the wrong branch, sorry. Intended to only have the fix in the pull request.
