### ISSUE TITLE
Extreme delay for Vector images to be shown

### ISSUE THREAD

**Issue by Yenthe666** [paulpatarinski/Xamarin.Forms.Plugins#33]
Hi Paul,

First of all, thank you very much for this library and the time you've spent on this!
I do notice one problem though. I've added all your plugins for Android, iOS and Windows and set up the Init for every platform. I then created a new ViewModel named ViaXamlViewModel.cs which looks like this:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Begijnhoeve.ViewModel
{
    public class ViaXamlViewModel
    {
        public Assembly SvgAssembly
        {
            get { return typeof(App).GetTypeInfo().Assembly; }
        }

        public string CollegasSvgPath
        {
            get { return "Begijnhoeve.Images.collegas.svg"; }
        }
    }
}
```
I've added a folder Images which contains the SVG file 'collegas.svg' with the following code in it:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve" height="100px" width="100px">
<g>
	<path fill="#7F7D66" d="M39.8,34.9c0,1.2-1,2.1-2.1,2.1h-7.1c-1.2,0-2.1-1-2.1-2.1v-7.1c0-1.2,1-2.1,2.1-2.1h2.1v-4.2H21.4v4.2h2.1
		c1.2,0,2.1,1,2.1,2.1v7.1c0,1.2-1,2.1-2.1,2.1h-7.1c-1.2,0-2.1-1-2.1-2.1v-7.1c0-1.2,1-2.1,2.1-2.1h2.1v-4.2H7.3v4.2h2.1
		c1.2,0,2.1,1,2.1,2.1v7.1c0,1.2-1,2.1-2.1,2.1H2.3c-1.2,0-2.1-1-2.1-2.1v-7.1c0-1.2,1-2.1,2.1-2.1h2.1v-4.2c0-1.5,1.3-2.8,2.8-2.8
		h11.3v-4.2h-2.1c-1.2,0-2.1-1-2.1-2.1V5.1c0-1.2,1-2.1,2.1-2.1h7.1c1.2,0,2.1,1,2.1,2.1v7.1c0,1.2-1,2.1-2.1,2.1h-2.1v4.2h11.3
		c1.5,0,2.8,1.3,2.8,2.8v4.2h2.1c1.2,0,2.1,1,2.1,2.1V34.9z"/>
</g>
</svg>
```

In the view I call the image like this:
```
          <StackLayout Orientation="Horizontal" Padding="25,0">
            <abstractions:SvgImage SvgAssembly="{Binding SvgAssembly}" SvgPath="{Binding CollegasSvgPath}" HeightRequest="50" WidthRequest="50" HorizontalOptions="Start"/>
          </StackLayout>
```

However when I now launch my app and view this page it will take +-10 seconds before the image shows up. The room is reserved and is not showing any images and after 10 seconds it 'pops' up.
In my output I can see it starts a Thread and soon after it will pause for x seconds (around 10).
The output:
```
Thread started: <Thread Pool> #9
05-22 13:29:11.235 I/art     (29683): Explicit concurrent mark sweep GC freed 459(18KB) AllocSpace objects, 0(0B) LOS objects, 20% free, 62MB/78MB, paused 1.013ms total 11.711ms
05-22 13:29:11.236 D/Mono    (29683): GC_OLD_BRIDGE num-objects 36 num_hash_entries 36 sccs size 36 init 0.00ms df1 0.16ms sort 0.00ms dfs2 0.15ms setup-cb 0.02ms free-data 0.04ms links 0/0/0/0 dfs passes 72/36
05-22 13:29:11.236 D/Mono    (29683): GC_MINOR: (Nursery full) pause 7.06ms, total 7.24ms, bridge 12.73ms promoted 1024K major 2608K los 1117K
05-22 13:29:16.316 I/art     (29683): Explicit concurrent mark sweep GC freed 327(13KB) AllocSpace objects, 0(0B) LOS objects, 20% free, 62MB/78MB, paused 916us total 11.773ms
05-22 13:29:16.317 D/Mono    (29683): GC_OLD_BRIDGE num-objects 27 num_hash_entries 27 sccs size 27 init 0.00ms df1 0.15ms sort 0.00ms dfs2 0.13ms setup-cb 0.03ms free-data 0.04ms links 0/0/0/0 dfs passes 54/27
05-22 13:29:16.317 D/Mono    (29683): GC_MINOR: (Nursery full) pause 8.91ms, total 9.20ms, bridge 12.82ms promoted 1280K major 3888K los 2401K
05-22 13:29:16.555 D/Mono    (29683): Assembly Ref addref NGraphics[0xb4b85ac0] -> System.Runtime.Extensions[0xb4b7fe20]: 4
```

What is the reason for this and how can this be improved? I have a high-end dev machine so that cannot be the cause. It seems that the Nursery is constantly full causing this delay or is it the thread simply pausing because it is still waiting for the Assembly Ref?

**Comment by Yenthe666** [comment]
I think this is the same as your issue?
https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/18

**Comment by Yenthe666** [comment]
Little update: I've tested this on iOS and there seems to be a significant delay in loading the app when using the vector images too. It 'holds' the app for a few seconds.

**Comment by paulpatarinski** [comment]
Hey @Yenthe666 sorry for the delayed response. 

Can you try running the sample app from the repo? Is that slow for you?
Also what device are you running?

**Comment by Yenthe666** [comment]
Hey @paulpatarinski no problem for the delay.

The sample app runs almost instantly and does not seem to have the delay.. Any ideas why the sample app doesn't seem to be affected but mine is? I've simply added your projects in to mine, like this:
<img src="http://i.imgur.com/hbO5mXR.png" alt="Project setup"/>
I'm running this on a Nexus 6 and iPhone 5C.

**Comment by erikarenhill** [comment]
The problem is with the doctype, remove doctype element from the svg file and it loads instantly. I think it tries to load the dtd file or something, have not investigated it, but had the same problem and I always remove the illustrator export comment and doctype then it works properly

**Comment by Yenthe666** [comment]
Hi @erikarenhill,

Do you mean this line? So that is the only thing I should change/remove?
```
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
```

I'll give this a test when I'm back in the office, I'll keep you guys updated.

**Comment by erikarenhill** [comment]
@Yenthe666 yes, remove that line and see if it's the same issue that I had

**Comment by paulpatarinski** [comment]
@Yenthe666 I have validated @erikarenhill 's proposed fix. If you comment out the DOCTYPE the render time does increase significantly.

**Comment by Yenthe666** [comment]
@paulpatarinski and @erikarenhill confirmed! This does indeed speed up the rendering by a lot, no more apparent problems then! :+1:
