### ISSUE TITLE
abstractions:SvgImage in ListView ViewCell

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#36]
This isn't really a common issue, but I can't figure it out to save my life, so i'm hoping someone here has come across it and knows how to fix it. I'm using `abstractions:SvgImage` in my project and it works great, but when I try to use it in a `ListView` `ViewCell` I get the error `Object reference not set to an instance of an object`. It seems that it can't find the `abstractions:SvgImage` when in the `ViewCell`, but i'm not sure how to make it so it can find it.

**Comment by paulpatarinski** [comment]
@JoshuaNovak919 I will take a look this weekend.

**Comment by JoshuaNovak919** [comment]
@paulpatarinski Thanks!! It seems to happen with other add-ons too. Not sure if there is a special way to reference the `abstractions:SvgImage` in a list view or if there is a special context to pass.

**Comment by paulpatarinski** [comment]
Hey @JoshuaNovak919 I got a fix for this for iOS and Win Phone (Android seems to still have an issue). I will let you know when the nuget is out. Performance seems to suck, so I will have to work on that at some point in the future...

**Comment by paulpatarinski** [comment]
#68 will be used for more updates on this
