### ISSUE TITLE
can't compile library or sample project

### ISSUE THREAD

**Issue by georgejecook** [paulpatarinski/Xamarin.Forms.Plugins#39]
I use xamarin studio, perhaps that's the cause; and had to hunt around to see your ngraphics fork to realized why it wouldn't compile.

1. could you put a refernece to that in the docs (saw another noob struggling with it),
2. is there anythign you can do to package your changes with your library?

**Comment by paulpatarinski** [comment]
Hey @georgejecook 

Can you elaborate a little bit, are you not able to compile the solution under SampleApp\PluginSampleApp? What are the compilation errors you are seeing? Also what do you mean by package changes with the library? 

p.s. Excited to try out your FastCell looks really promising.

**Comment by georgejecook** [comment]
Hi Paul,

It seems your additions to NGraphics are missing. You added some parser stuff in a diferent namespace. I saw you forked NGraphics, and the comment on your name space choice was to avoid collisions. When I pulled down the project it wouldn't build for me, as your fork of Ngraphics was nowhere to be seen.

I saw other comments on the xamarin forums from guys who couldn't get past this either.

I'm glad you see value in the FastCell. It's very much changed how I write my forms apps :)

**Comment by georgejecook** [comment]
a bit more info. I'm currently trying to build with a reference to your NGraphics forked project, which contains the missing Parsers classes; but alas it doens't build either. It can't find ApplePlatform, and if I add the standard NGraphics nuget package, I get a ton of naming collisions and nothing compiles. 

What I've seen so far is very interesting; but I need to be able to poke around in the source for our uses (we need to make buttons with this) - What can I do to get it to compile? I must be doing somethign wrong, as I presume you'd have a ton of "I can't compile from source" issues, otherwise.

**Comment by paulpatarinski** [comment]
@georgejecook figured it out. It was a gitignore fail :( I had the Custom Ngraphics assemblies in a ext_bin folder. https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG/SVG/SVG.Forms.Plugin.iOS/ext_bin

But they were not checked into source because of gitignore. If you pull latest should be fixed.

Let me know if you are still seeing issues. Also can you point me to the Forums post of that other person struggling? 

Cheers

**Comment by georgejecook** [comment]
update. it looks like for some reason you don't have the ext_bin folder for iOS.
Converesely, and rather sadly, the files to fix this are not in your public repo for the NGraphics fork either. I tried using that instead; but it ends up in compile errors which I can't resolve.

![http://oi62.tinypic.com/2el7ez9.jpg](http://oi62.tinypic.com/2el7ez9.jpg)
I'm extremely keen to work with your excellent library (great work btw; my team here are very excited about it - you can expect contributions ;) ). I'll build on the public nuget package for now, despite it hampering my ability to make the forms button class your library deserves (highlight/disabled/selected states - all with high efficiency). 

Best regards George.

**Comment by georgejecook** [comment]
ha! I got your mail as I pressed comment ;) I'll give it a whirl.

**Comment by paulpatarinski** [comment]
To elaborate a little more I have changed NGraphics a lot in my fork and I don't see it being merged into master. That being said someone had an issue of using NGraphics as well as this library to avoid the conflict I suffixed my forked assemblies with .Custom. The assemblies you see under ext_bin were from building the NGraphics fork in Release mode. If you have the time open an issue under the NGraphics fork with the compilation errors there...I will fix that one as well.

**Comment by georgejecook** [comment]
I can’t see how to raise an issue at : https://github.com/paulpatarinski/NGraphics <https://github.com/paulpatarinski/NGraphics>

thx

**Comment by paulpatarinski** [comment]
Did you get it to build?

**Comment by georgejecook** [comment]
Yes. Built fine. 

It's very impressive. Great work!

**Comment by paulpatarinski** [comment]
Thanks

Are you cool with closing this issue at this point?
