### ISSUE TITLE
Assembly with Xaml?

### ISSUE THREAD

**Issue by onovotny** [paulpatarinski/Xamarin.Forms.Plugins#4]
Can the SvgImage be used in XAML? What'd be the syntax to set the Assembly property?

**Comment by paulpatarinski** [comment]
@onovotny I made both the Assembly and Path properties bindable and added a sample xaml usage to the Project page. https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG

<abstractions:SvgImage Grid.Row="0" Grid.Column="0" SvgAssembly="{Binding SvgAssembly}" SvgPath="{Binding CoolMaskSvgPath}" HeightRequest="50" WidthRequest="50" BackgroundColor="White" HorizontalOptions="Center" VerticalOptions="Center"/>

If you pull 1.0.0.12 of the nuget package you should be able to use the Xaml implementation.

**Comment by paulpatarinski** [comment]
@onovotny did the xaml solution work for you?
