### ISSUE TITLE
KeyboardOverlap not working

### ISSUE THREAD

**Issue by fcogutierrez** [paulpatarinski/Xamarin.Forms.Plugins#41]
Hello.

I followed all the instructions, but the keyboard does the same behavior over the layout (hiding the bottom side).

I installed the nuget package in the iOS project and then I did the initialization after global::Xamarin.Forms.Forms.Init();

**Comment by paulpatarinski** [comment]
Do you by any chance have other PageRenderers in your iOS project?

Can you create a sample project or submit a pull request to this project demonstrating the issue?

What does your UI look like? Can you post the page that is not working?

**Comment by fcogutierrez** [comment]
@paulpatarinski, this is the page:

<?xml version="1.0" encoding="utf-8" ?>
<base:ContentPageBase xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:base="clr-namespace:Elfo.VisionMobile.Core.Views.Base;assembly=Elfo.VisionMobile.Core"
             xmlns:resources="clr-namespace:Elfo.VisionMobile.Core.Resources;assembly=Elfo.VisionMobile.Core"
             xmlns:controls="clr-namespace:Elfo.VisionMobile.Core.Controls;assembly=Elfo.VisionMobile.Core"
             x:Class="Elfo.VisionMobile.Core.Views.OrderProposalView"
             Title="Order Proposal" Style="{StaticResource DefaultContentPage}">

  <Grid>
      <Grid RowSpacing="{StaticResource GridWithListSpacing}">
        <Grid.RowDefinitions>
          <RowDefinition Height="auto"/>
          <RowDefinition Height="*"/>
          <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>

        <SearchBar x:Name="OrderProposalSearchBar" Grid.Row="0" Style="{StaticResource AppSearchBar}" Text="{Binding ItemKey, Mode=TwoWay}" Placeholder="{resources:Translate SearchPlaceholder}"
                   SearchCommand="{Binding SearchItemsCommand}"/>

        <ListView x:Name="ItemsListView" Grid.Row="1" Style="{StaticResource AppListView}" ItemsSource="{Binding OrderProposalLines}"
                  IsVisible="{Binding Items, Converter={StaticResource NullToIsVisibleConverter}}" ItemSelected="OnItemSelected"
                  ItemTemplate="{StaticResource AdjustableItemsListViewTemplate}"/>

        <ContentView Grid.Row="2" Padding="{StaticResource FullSpace}" VerticalOptions="FillAndExpand">
          <Button Style="{StaticResource DefaultButton}" VerticalOptions="FillAndExpand"
                  Text="{resources:Translate SendOrderProposal}" Command="{Binding PostInventoryCommand}"/>
        </ContentView>
      </Grid>
</base:ContentPageBase>

**Comment by paulpatarinski** [comment]
I see, I never tested with a SearchBar (only Entries). I will take a look at adding support for SearchBar.

**Comment by fcogutierrez** [comment]
Ok @paulpatarinski, just waiting :-)

**Comment by paulpatarinski** [comment]
hey @fcogutierrez 

Had a chance to look at your example more. You are having a completely different issue. It is not that that search bar is overlapped or that an entry is overlapped it is a button at the bottom of your page. 

<img width="376" alt="sendbtnoverlap" src="https://cloud.githubusercontent.com/assets/7964134/8588468/8d41185a-25d0-11e5-871c-efa0d95d824d.png">

This plugin aims to resolve an issue with the Keyboard on iOS overlapping input controls as described here https://forums.xamarin.com/discussion/comment/133722/#Comment_133722

I would suggest using LayoutTo in your case to move the submit button above the keyboard. Something in the lines of : 

```
var oldBounds = myBtn.Bounds;
var keyboardHeight = GetKeyboardHeight();
var newBounds = new Rect(oldBounds.X,oldBounds.Y + keyboardHeight,oldBounds.Height,oldBounds.Width);
myBtn.LayoutTo(newBounds);
```

Let me know if that helps.

**Comment by fcogutierrez** [comment]
Hello @paulpatarinski, first of all, thanks about your help :-)

Secondly, where should I place that code?

Thanks again!!

**Comment by paulpatarinski** [comment]
You can tap into the Entry TextChange event http://developer.xamarin.com/api/event/Xamarin.Forms.Entry.TextChanged/

In the event handler check if they have some text entered and run the code above. 

The Keyboard overlap Custom renderer has some examples of LayoutTo

https://github.com/paulpatarinski/Xamarin.Forms.Plugins/blob/master/KeyboardOverlap/KeyboardOverlap/KeyboardOverlap.Forms.Plugin.iOSUnified/KeyboardOverlapRenderer.cs

```
private void ShiftPageDown (nfloat keyboardHeight, double activeViewBottom)
		{
			var pageFrame = Element.Bounds;

			var newY = pageFrame.Y - CalculateShiftByAmount (pageFrame.Height, keyboardHeight, activeViewBottom);

			Element.LayoutTo (new Rectangle (pageFrame.X, newY,
				pageFrame.Width, pageFrame.Height));

			_pageWasShiftedUp = false;
		} 
```
