### ISSUE TITLE
RoundedBoxView round inner content/half circle

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#47]
Is there a way to round the content in the box, for example an image or another box view. Is there a way to make a half circle?

**Comment by paulpatarinski** [comment]
Hey Josh, 

From my knowledge the BoxView does not support having children or content, which makes the first case you are suggesting impossible. 

There is not way to make half a circle just by using the RoundedBoxView. 

Now all that being said. Here are some suggestions on how to accomplish what you are trying to do.

1. Create a RelativeLayout > Add RoundedBoxView as a child > Add the other content you want(image another boxview) and set the height and width to be less then the one of the RoundedBoxView which would constrain it to the inside of the circle
2. RelativeLayout > RoundedBoxView (to make your circle) > Add BoxView that is correctly positioned to cover the part of the Circle you don't want to display

**Comment by JoshuaNovak919** [comment]
@paulpatarinski Thanks for the help. I ended up using `canvas.DrawPath` with `NControl` for now. It's not the best way to handle it, but it'll do until I have time to figure something better out.
