### ISSUE TITLE
ExtendedMapRenderer on iOS doesn't appear on nugget package

### ISSUE THREAD

**Issue by codercampos** [paulpatarinski/Xamarin.Forms.Plugins#54]
I recently download the plugin from nuget but when I want to add the Renderer Init it simple does not appear anywhere, like if the package does not exists on iOS. For the moment I will download the plugin and compile it myself. Or maybe I'm doing something wrong.

Regards

Btw: I download the package from Nuget in VS

**Comment by paulpatarinski** [comment]
@codercampos I just released [1.5.0](https://www.nuget.org/packages/Xam.Plugins.Forms.ExtendedMap/1.5.0) which is an Alpha release of what the final control should look and feel like. That now has an iOS implementation as well. Let me know if you are having trouble getting it to work.

**Comment by paulpatarinski** [comment]
@codercampos did you get a chance to test this?

**Comment by codercampos** [comment]
I haven't I have to use my own implementation for a quick release to the customer. I will try this tonight and give you feedback to close this issue. Thanks in advance and such a great work btw :+1:
