### ISSUE TITLE
Android NGraphics.Android.Resource is defined multiple times

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#58]
I am getting the message `NGraphics.Android.Resource is defined multiple times` when I use NControl and this SVG plugin. Anyone know how to fix this?

**Comment by JoshuaNovak919** [comment]
Anyone? :(

**Comment by paulpatarinski** [comment]
Hey Josh. Can you throw together a sample that demos the issue? It would help me resolve it. Both NControl and the SVG plugin use NGraphics under the hood have had issues with that before.

**Comment by JoshuaNovak919** [comment]
I'll throw one together in about an hour when I get home. Basically any project you add this plugin and NControl to has the issue on Android

**Comment by JoshuaNovak919** [comment]
Here is the sample project. It works in iOS, but won't build for Android because of the issue. I'm hoping you have an idea on how to fix it, cause i'm at a loss. I haven't done much with Android before.

https://drive.google.com/file/d/0B68aZqcn2sxXdjdZX08tVEF2U28/view?usp=sharing

**Comment by JoshuaNovak919** [comment]
@paulpatarinski Even if you find/know of a way to temporarily fix it let me know. I need to prepare the Android version for launch soon and I can't even get it to build.

**Comment by JoshuaNovak919** [comment]
Also, for reference, this is the full line it is giving me trouble with because it is repeated:

`global::NGraphics.Android.Resource.String.library_name = global::svgnc.Droid.Resource.String.library_name;`

**Comment by JoshuaNovak919** [comment]
@paulpatarinski You happen to get a chance to look at this? I'm still stuck on how I can fix this.

**Comment by JoshuaNovak919** [comment]
@paulpatarinski It looks like this may be as simple as changing:

`<string name="library_name">NGraphics.Android</string>`

to

`<string name="library_name">NGraphics.Android.Custom</string>`

in your custom NGraphics Strings.xml file.

`NGraphics/Platforms/NGraphics.Android/Resources/values/Strings.xml`

although I don't know how to make this a dll for the SVG plugin.

**Comment by paulpatarinski** [comment]
Hey Josh, 

I am thinking the same thing. Need to use custom namespace I have started working on it in my NGraphics fork. Pretty close to getting it done.

**Comment by JoshuaNovak919** [comment]
@paulpatarinski Oh ok awesome! I was about to try it myself, but i'm not really sure what i'm doing with that stuff. Haven't done anything with Android before.

**Comment by paulpatarinski** [comment]
@JoshuaNovak919 I have changed all the NGraphics assemblies to have a suffix of Custom. Check out V 1.0.0.26 https://www.nuget.org/packages/Xam.Plugins.Forms.Svg/. Let me know if it resolves the issue (did for me in a sample project)

**Comment by paulpatarinski** [comment]
Josh any luck?

**Comment by JoshuaNovak919** [comment]
@paulpatarinski I'll be testing it shortly. I couldn't wait before so I built it myself based off the code you had worked on etc, so I need to switch it out and make sure it is still working.

**Comment by JoshuaNovak919** [comment]
@paulpatarinski Looks good. Thanks!!
