### ISSUE TITLE
RoundedBoxView radius lost on animation

### ISSUE THREAD

**Issue by andreagiunta** [paulpatarinski/Xamarin.Forms.Plugins#59]
I made a switch control with two roundedboxview (rbv). The base rbv has a corner radius set to 20d, the inside view is a circle with 360 corner radius.
The animation is simple, i move the inside rbv edge to edge. And it works great.
But if i change the color of the base rbv, during the animation, the rbv lose is corner radius property and i cannot set again.
Tested on android.
![correct status](https://cloud.githubusercontent.com/assets/12980538/9810805/8f0b727c-5873-11e5-92a7-0d5346fd7e1d.png)
![losecorner](https://cloud.githubusercontent.com/assets/12980538/9810807/8f10c6a0-5873-11e5-8090-4c495716fcb1.png)
![losecorner2](https://cloud.githubusercontent.com/assets/12980538/9810806/8f0cda4a-5873-11e5-98ec-bf27540ddaf7.png)

**Comment by paulpatarinski** [comment]
First of all awesome work, never thought that the RoundedBoxView would be used to create other controls. Can you put together a sample, which demos the issue?

**Comment by andreagiunta** [comment]
Hi.
I'm glad you appreciate.
Sorry for the delay but i'm really busy right now.
I made a try today with:

-a roundboxview
-an svg of a white circle

this two elements are added in a relative layout and still doesn't work.

anyway i've removed using and namespaces, you have to modify the
BoxView baseView = new BoxView() with a roundboxview to reproduce.
Hope this can help.

Have a nice day

2015-09-21 18:25 GMT+02:00 Paul P <notifications@github.com>:

> First of all awesome work, never thought that the RoundedBoxView would be
> used to create other controls. Can you put together a sample, which demos
> the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/59#issuecomment-142034069>
> .
>



-- 
Andrea Giunta

[image: Immagine in linea 1]
Microsoft Azure MVP 2015
Senior Mobile Developer @ Garoo S.r.l.
CTO @ICSoftwareSolution S.R.L.S.
Microsoft Azure Tour Owner - South & Center Italy 2013/2014

﻿
    /// <summary>
    /// A custom switch based only on view with maincolor
    /// </summary>
    public class CustomSwitchView : RelativeLayout
    {
        /// <summary>
        /// The base rounded view with background color equal to app maincolor
        /// </summary>
        BoxView baseView = new BoxView()
        {
            WidthRequest = 50,
            HeightRequest = 30,
            BackgroundColor = Xamarin.Forms.Color.FromHex(Settings.MainColor),
        };

        /// <summary>
        /// The toogle circle
        /// </summary>
        SvgImage toogle = Helpers.GraphicsElements.GetSvgImage("ic_dot_white",20);

        /// <summary>
        /// Bool value, if true user swicthed on, otherwise off
        /// </summary>
        bool isToogled = false;
        public bool IsToogled
        {
            get
            {
                return isToogled;
            }
            set
            {
                isToogled = value;
                ToogledChangeStatus(this);
            }
        }

        public delegate void ToggledEventHandler(object sender);
        public event ToggledEventHandler ToogledChangeStatus;

        TapGestureRecognizer tgs = new TapGestureRecognizer();

        public CustomSwitchView()
        {
            this.Children.Add(baseView,
                              Constraint.Constant(0),
                              Constraint.Constant(0));
            this.Children.Add(toogle,
                              Constraint.RelativeToView(baseView,(par,sib)=>sib.X +5),
                              Constraint.RelativeToView(baseView,(par,sib)=>sib.Y +5));
            tgs.Tapped += tgs_Tapped;
            this.toogle.GestureRecognizers.Add(tgs);
            this.baseView.GestureRecognizers.Add(tgs);
            this.GestureRecognizers.Add(tgs);
            ToogledChangeStatus += CustomSwitchView_ToogledChangeStatus;
            this.SizeChanged += (s, e) => 
            { 
                ToogledChangeStatus(this); 
            };
            
        }

        void CustomSwitchView_ToogledChangeStatus(object sender)
        {
            setTooglePosition();
            setColor();
        }

        void tgs_Tapped(object sender, EventArgs e)
        {
            animateToogle();
            isToogled = !isToogled;
            setColor();
        }

        void animateToogle()
        {
            if (isToogled)
            {
                toogle.TranslateTo(toogle.AnchorX, toogle.AnchorY,250, Easing.CubicInOut);
            }
            else
            {
                toogle.TranslateTo(baseView.Width - toogle.Width - 10, toogle.AnchorY,250, Easing.CubicInOut);
            }
        }

        void setTooglePosition()
        {
            if (isToogled)
            {
                toogle.TranslateTo(baseView.Width - toogle.Width - 10, toogle.AnchorY, 250, Easing.CubicInOut);
            }
            else
            {
                toogle.TranslateTo(toogle.AnchorX, toogle.AnchorY, 250, Easing.CubicInOut);
            }
        }

        void setColor()
        {
            Color background;
            if (isToogled)
                background= Color.FromHex(Settings.MainColor);
            else
                background = Color.FromHex(Settings.ActionBarColor);
            baseView.SetValue(BackgroundColorProperty, background);
        }
    }

**Comment by paulpatarinski** [comment]
@andreagiunta I hacked this together quickly so it might not be exactly what you are looking for but should get you on the right track

```
using Xamarin.Forms;
using System.Threading.Tasks;

namespace SampleApp.Pages
{
	public class SwitchPage : ContentPage
	{
		public SwitchPage ()
		{
			var relativeLayout = new RelativeLayout () {
				VerticalOptions = LayoutOptions.Center,
				HorizontalOptions = LayoutOptions.Center
			};

			var switchControl = new RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView {
				BackgroundColor = Color.FromHex ("#BDBDBD"),
				CornerRadius = 25,
				WidthRequest = 300,
				HeightRequest = 50
			};


			relativeLayout.Children.Add (switchControl,
				Constraint.RelativeToParent ((parent) => {
					return parent.Width * 0.05;
				}),
				Constraint.RelativeToParent ((parent) => {
					return parent.Height * 0.4;
				}));

			var switchKnob = new RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView {
				BackgroundColor = Color.White,
				BorderColor = Color.FromHex ("#E0E0E0"),
				BorderThickness = 1,
				CornerRadius = 25,
				WidthRequest = 50,
				HeightRequest = 50
			};

			relativeLayout.Children.Add (switchKnob,
				Constraint.RelativeToParent ((parent) => {
					return parent.Width * 0.05;
				}),
				Constraint.RelativeToParent ((parent) => {
					return parent.Height * 0.4;
				}));

			switchControl.GestureRecognizers.Add (new TapGestureRecognizer (r => ToggleSwitch (switchKnob, switchControl)));


			Content = relativeLayout;
		}

		private bool _isOn = false;
		private bool _isAnimating = false;

		Rectangle _knobOffBounds;

		private async void ToggleSwitch (RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView knob, RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView switchControl)
		{
			if (_isAnimating)
				return;
			
			if (!_isOn) {
				var switchBounds = switchControl.Bounds;
				_knobOffBounds = knob.Bounds;
				var knobNewBounds = new Rectangle ((switchBounds.Width + switchBounds.X) - _knobOffBounds.Width, _knobOffBounds.Y, _knobOffBounds.Width, _knobOffBounds.Height);

				_isAnimating = true;

				var moveAnimationTask = knob.LayoutTo (knobNewBounds, 750, Easing.CubicOut);

				var colorChangeTask = Task.Delay (400).ContinueWith ((r) => {
					Device.BeginInvokeOnMainThread (() => {
						switchControl.BackgroundColor = Color.FromHex ("#FFEB3B");
					});
				});

				await Task.WhenAll (moveAnimationTask, colorChangeTask);

				_isOn = true;
				_isAnimating = false;
			} else {
				_isAnimating = true;

				var moveAnimationTask = knob.LayoutTo (_knobOffBounds, 750, Easing.CubicOut);

				var colorChangeTask = Task.Delay (400).ContinueWith ((r) => {
					Device.BeginInvokeOnMainThread (() => {
						switchControl.BackgroundColor = Color.FromHex ("#BDBDBD");
					});
				});

				await Task.WhenAll (moveAnimationTask, colorChangeTask);

				_isOn = false;
				_isAnimating = false;
			}
		}
	}
}


```

![ios simulator screen shot oct 17 2015 12 11 14 pm](https://cloud.githubusercontent.com/assets/7964134/10560178/39a91412-74c8-11e5-9e27-4573ed578d87.png)


![ios simulator screen shot oct 17 2015 12 11 48 pm](https://cloud.githubusercontent.com/assets/7964134/10560181/43b4584a-74c8-11e5-889e-9d8ef8b7b43b.png)

**Comment by andreagiunta** [comment]
Thanks i'll try asap.
On this project due to timing we fixed with an svg, but know i want to know
Really appreciate it



2015-10-17 19:12 GMT+02:00 Paul P <notifications@github.com>:

> @andreagiunta <https://github.com/andreagiunta> I hacked this together
> quickly so it might not be exactly what you are looking for but should get
> you on the right track
>
> using Xamarin.Forms;
> using System.Threading.Tasks;
>
> namespace SampleApp.Pages
> {
>     public class SwitchPage : ContentPage
>     {
>         public SwitchPage ()
>         {
>             var relativeLayout = new RelativeLayout () {
>                 VerticalOptions = LayoutOptions.Center,
>                 HorizontalOptions = LayoutOptions.Center
>             };
>
>             var switchControl = new RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView {
>                 BackgroundColor = Color.FromHex ("#BDBDBD"),
>                 CornerRadius = 25,
>                 WidthRequest = 300,
>                 HeightRequest = 50
>             };
>
>
>             relativeLayout.Children.Add (switchControl,
>                 Constraint.RelativeToParent ((parent) => {
>                     return parent.Width * 0.05;
>                 }),
>                 Constraint.RelativeToParent ((parent) => {
>                     return parent.Height * 0.4;
>                 }));
>
>             var switchKnob = new RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView {
>                 BackgroundColor = Color.White,
>                 BorderColor = Color.FromHex ("#E0E0E0"),
>                 BorderThickness = 1,
>                 CornerRadius = 25,
>                 WidthRequest = 50,
>                 HeightRequest = 50
>             };
>
>             relativeLayout.Children.Add (switchKnob,
>                 Constraint.RelativeToParent ((parent) => {
>                     return parent.Width * 0.05;
>                 }),
>                 Constraint.RelativeToParent ((parent) => {
>                     return parent.Height * 0.4;
>                 }));
>
>             switchControl.GestureRecognizers.Add (new TapGestureRecognizer (r => ToggleSwitch (switchKnob, switchControl)));
>
>
>             Content = relativeLayout;
>         }
>
>         private bool _isOn = false;
>         private bool _isAnimating = false;
>
>         Rectangle _knobOffBounds;
>
>         private async void ToggleSwitch (RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView knob, RoundedBoxView.Forms.Plugin.Abstractions.RoundedBoxView switchControl)
>         {
>             if (_isAnimating)
>                 return;
>
>             if (!_isOn) {
>                 var switchBounds = switchControl.Bounds;
>                 _knobOffBounds = knob.Bounds;
>                 var knobNewBounds = new Rectangle ((switchBounds.Width + switchBounds.X) - _knobOffBounds.Width, _knobOffBounds.Y, _knobOffBounds.Width, _knobOffBounds.Height);
>
>                 _isAnimating = true;
>
>                 var moveAnimationTask = knob.LayoutTo (knobNewBounds, 750, Easing.CubicOut);
>
>                 var colorChangeTask = Task.Delay (400).ContinueWith ((r) => {
>                     Device.BeginInvokeOnMainThread (() => {
>                         switchControl.BackgroundColor = Color.FromHex ("#FFEB3B");
>                     });
>                 });
>
>                 await Task.WhenAll (moveAnimationTask, colorChangeTask);
>
>                 _isOn = true;
>                 _isAnimating = false;
>             } else {
>                 _isAnimating = true;
>
>                 var moveAnimationTask = knob.LayoutTo (_knobOffBounds, 750, Easing.CubicOut);
>
>                 var colorChangeTask = Task.Delay (400).ContinueWith ((r) => {
>                     Device.BeginInvokeOnMainThread (() => {
>                         switchControl.BackgroundColor = Color.FromHex ("#BDBDBD");
>                     });
>                 });
>
>                 await Task.WhenAll (moveAnimationTask, colorChangeTask);
>
>                 _isOn = false;
>                 _isAnimating = false;
>             }
>         }
>     }
> }
>
>
>
> [image: ios simulator screen shot oct 17 2015 12 11 14 pm]
> <https://cloud.githubusercontent.com/assets/7964134/10560178/39a91412-74c8-11e5-9e27-4573ed578d87.png>
>
> [image: ios simulator screen shot oct 17 2015 12 11 48 pm]
> <https://cloud.githubusercontent.com/assets/7964134/10560181/43b4584a-74c8-11e5-889e-9d8ef8b7b43b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/59#issuecomment-148935086>
> .
>



-- 
Andrea Giunta

[image: Immagine in linea 1]
Microsoft Azure MVP 2015
Senior Mobile Developer @ Garoo S.r.l.
CTO @ICSoftwareSolution S.R.L.S.

**Comment by paulpatarinski** [comment]
I am gonna close this for now. I will reopen if needed
