### ISSUE TITLE
KeyboardOverlap slides more than it should

### ISSUE THREAD

**Issue by boomercoder** [paulpatarinski/Xamarin.Forms.Plugins#60]
Here are the screenshots. The yellow box is the Entry itself.

1. Shows the keyboard closed. The gray area in the bottom is a tab bar. You can ignore it.
2. Shows the keyboard in active state. Notice the the white area between the keyboard and the entry field.
3. Shows the state when the QuickType suggestions are closed by swiping down. The Entry field slides far above when you close the suggestions.

Here's the code for the UI:

```
Grid grid = new Grid {
	VerticalOptions = LayoutOptions.FillAndExpand,
	RowDefinitions = {
		new RowDefinition { Height = new GridLength (1, GridUnitType.Star) },
		new RowDefinition { Height = new GridLength (50, GridUnitType.Absolute) }
	},
	ColumnSpacing = 0,
	RowSpacing = 0
};

grid.Children.Add (new BoxView { Color = Color.Red });
grid.Children.Add (new Entry { BackgroundColor = Color.Yellow }, 0, 1);

Content = grid;
```
![1](https://cloud.githubusercontent.com/assets/10635384/9830169/b5246efa-592c-11e5-9e0b-fed3b06a2cc3.png)
![2](https://cloud.githubusercontent.com/assets/10635384/9830168/b5201cce-592c-11e5-8786-62602a79a7b4.png)
![3](https://cloud.githubusercontent.com/assets/10635384/9830167/b4edd3c2-592c-11e5-92fd-9eef128f9347.png)

**Comment by paulpatarinski** [comment]
This should be fixed in 1.0.0.4 

https://www.nuget.org/packages/Xam.Plugins.Forms.KeyboardOverlap/

There is still a slight shift that might happen if you have Quick Type enabled, then you disable and dismiss the keyboard, but that would be harder to fix and I would consider an edge case
