### ISSUE TITLE
SVG As ToolbarItem in Xamarin Forms

### ISSUE THREAD

**Issue by ChaseFlorell** [paulpatarinski/Xamarin.Forms.Plugins#62]
I haven't looked at it myself, but I'm wondering if there's a way to add an SVG as a Toolbar icon?

```xaml
<!-- pseudo code -->
<ContentPage.ToolbarItems>
    <abstractions:SvgToolbarItem Icon="my.svg" Order="Primary" Priority="0" />
</ContentPage.ToolbarItems>
```

**Comment by paulpatarinski** [comment]
I think the question would be what is ToolbarItems. If it is a collection of Views, I don't see why not. Never tried either.

**Comment by paulpatarinski** [comment]
Had a chance to look at this more. Short answer is without extending the ToolbarItems i.e. Custom Renderer can't do it. ToolbarItems is a collection of ToolbarItem https://developer.xamarin.com/api/type/Xamarin.Forms.ToolbarItem/

Icon is a string - FileImageSource. Gets or sets a string that identifies the image that is displayed on this ToolbarItem element.

In other words the implementation is too restrictive to allow for SVGs to be used.

**Comment by Emasoft** [comment]
It seems that ToolbarItems passes the string to an instance of **Xamarin.Forms.FileImageSource**. Can we extend **Xamarin.Forms.FileImageSource** to include SVG files?

**Comment by Vladis466** [comment]
Any update on the possibility of this extension? 

We use a common set of svg's in our pcl and it is inconvenient to have to use separate pngs for the toolbar.

**Comment by dazinator** [comment]
Is this possible yet?

**Comment by mateuswolkmer** [comment]
Update on the issue? It should be an enhancement, why is it closed?
