### ISSUE TITLE
SVG "desc" element is not supported on Xamarin.iOS

### ISSUE THREAD

**Issue by vhugogarcia** [paulpatarinski/Xamarin.Forms.Plugins#65]
Hello friends,
I implemented a demo app using Xamarin.Forms 1.5.x and this plugin looks really amazing on the capabilities, however I'm getting an error when trying to run the app on the iPhone simulator, Xamarin fires an error on "FinishedLaunching" event under AppDelegate.cs and the error is on line: LoadApplication(new App());

Any idea or workaround what I could be missing?

Note: I added the nuget plugin on the PCL project, and the iOS project.

My code used:
```
new SvgImage { 
							SvgPath = "MyDemoApp.Resources.Images.mail.svg",
							SvgAssembly = typeof(App).GetTypeInfo().Assembly, 
							HeightRequest = 100,
							WidthRequest = 100
						}
```

Thanks

**Comment by paulpatarinski** [comment]
Hey @vhugogarcia 

Open up your svg in a text editor (Notepad++) and search for "desc" elements. Get rid of those elements and try again

**Comment by vhugogarcia** [comment]
Thanks @paulpatarinski  for your faster response.

I removed "desc" element from the SVG file and now the error says: "SVG "mask" element is not supported

However, by removing that <mask> element the image is not like the original design. 

Any suggestions?

**Comment by paulpatarinski** [comment]
Currently only a subset of SVG elements are supported. My goal is to eventually support the full spec https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/26 

In the meantime I can think of the following options : 

* Try to achieve the same effect by using one of the other supported elements
* Remove the mask as a whole
* Try to add support for mask (based on my experience most elements are not hard to implement just time consuming to test)

Cheers
