### ISSUE TITLE
RoundedBoxView 1.0.0.6 is dependant to XF 1.4

### ISSUE THREAD

**Issue by heartquake** [paulpatarinski/Xamarin.Forms.Plugins#74]
I upgraded XF to 2.0.0.6490 and RoundedBoxView to 1.0.0.6. The plugin works perfect on Droid and iOS however I'm getting the error on WP8 project. The error disappears when I exclude the plugin from WP8.

Error	33	Cannot resolve reference assemblies. Please check the reference assemblies. Cannot resolve dependency to assembly 'Xamarin.Forms.Platform.WP8, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

**Comment by paulpatarinski** [comment]
This is a known issue with win phone projects not respecting the Forms version dependency. I will publish a version of the nuget for Forms 2.0. That should resolve your issue

**Comment by paulpatarinski** [comment]
1.0.0.7 is out with support for Forms 2.0

https://www.nuget.org/packages/Xam.Plugins.Forms.RoundedBoxView/

enjoy

**Comment by heartquake** [comment]
Thank you Paul.
