### ISSUE TITLE
Can't install package into PCL Profile 111

### ISSUE THREAD

**Issue by adrianknight89** [paulpatarinski/Xamarin.Forms.Plugins#83]
Hi,

I'm having difficulty installing this into Profile 111. Which profile(s) do you support?

> Could not install package 'Xam.Plugins.Forms.Svg 1.0.0.27'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by adrianknight89** [comment]
I tried 259. Same issue.

**Comment by EmilAlipiev** [comment]
Could you find a solution for this? or simply it doesnt support?

**Comment by EmilAlipiev** [comment]
Problem looks like with windows phone 8.1 project. if you remove it in the target list, you can add it.

**Comment by eventgenius** [comment]
Are there any plans to provide support for profile 111? The windows phone 8.1 project is really required in this case. Alterntively does anyone know of an alternative for a rounded `BoxView` with a border?

**Comment by Hoangphuvan** [comment]
> Problem looks like with windows phone 8.1 project. if you remove it in the target list, you can add it.
I have tried to the instruction but the problem still occurs. Does anyone help?

**Comment by pallavbohara** [comment]
@EmilAlipiev  Me too getting the same problem tried to remove Windows 8.1 but giving this error.
![image](https://cloud.githubusercontent.com/assets/23195991/26537578/5dcf7072-445e-11e7-8188-fe7ca06bc922.png)
